/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.Acccontact_nameForm;
import com.forms.ContactHistoryForm;
import com.forms.ContactnameForm;

public class Acccontact_nameAction extends DispatchAction {
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Acccontact_nameForm contactnameForm = (Acccontact_nameForm) form;// TODO Auto-generated method stub
		return mapping.findForward("display");
	}
	
	public ActionForward display1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Acccontact_nameForm contactnameForm = (Acccontact_nameForm) form;// TODO Auto-generated method stub
		return mapping.findForward("display1");
	}
	/*public ActionForward displayrecord(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Acccontact_nameForm contactnameForm = (Acccontact_nameForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		String com=(String) session.getAttribute("companyname");
		System.out.println("inside action class");
		Connection con = DBUtil.openConnection();
		System.out.println("connection------"+con);
	     try { 
	     Statement stmt = (Statement) con.createStatement();
	      
	        String sql = "Select NAME From CONTACT_MANAGEMENT WHERE COMPANY = '"+com+"' ORDER BY NAME ASC";
	       
	        ResultSet rs = stmt.executeQuery(sql);
	        ArrayList<String> List1 = new ArrayList<String>();
	        while (rs.next()) {

	            List1.add(rs.getString("NAME"));
	            
	      }
	        if( List1!=null){
	         System.out.println("inside if");
	         session.setAttribute("plist",  List1);
	      return mapping.findForward("display");
	      
	        }
	     }catch(Exception e){
	      e.printStackTrace();
	     }
	     
	 
		return mapping.findForward("display");
	}
	*/
	public ActionForward displayHistory(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		Acccontact_nameForm cf = (Acccontact_nameForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		String com=(String) session.getAttribute("companyname");
	    String query = (String)request.getParameter("name");

		System.out.println("name="+query);
		Connection con = DBUtil.openConnection();
		Statement stmt = con.createStatement();
		ResultSet rs=null;

        if (query.equalsIgnoreCase("All")) {
        	String Sql1 = "SELECT * FROM CONTACT_MANAGEMENT WHERE COMPANY = '"+com+"' ORDER BY ID ASC";

    		ArrayList a1 = new ArrayList();

    		try {
    			stmt = con.createStatement();
    			rs = stmt.executeQuery(Sql1);
    			while (rs.next()) {
    				ContactHistoryForm con1=new ContactHistoryForm();
    				con1.setSlno1(rs.getString(1));
    				con1.setName1(rs.getString(2));
    				con1.setPlace1(rs.getString(3));
    				con1.setContact1(rs.getString(4));
    				con1.setRemarks1(rs.getString(5));
    				con1.setUnit1(rs.getString(6));
    			
    				a1.add(con1);
    			}
    			
    			rs.close();
    			stmt.close();
    			con.close();
    		} catch (Exception e) {
    			e.printStackTrace();
    		}
    		request.setAttribute("empmaster", a1);
    		
		}
        else {
        	String Sql = "SELECT * FROM CONTACT_MANAGEMENT WHERE UPPER(NAME) like '%' || UPPER('"+query+"') || '%' AND COMPANY = '"+com+"'";
    		
    		ArrayList a = new ArrayList();

    		try {
    			stmt = con.createStatement();
    			rs = stmt.executeQuery(Sql);
    			while (rs.next()) {
    				ContactHistoryForm con1=new ContactHistoryForm();
    				con1.setSlno1(rs.getString(1));
    				con1.setName1(rs.getString(2));
    				con1.setPlace1(rs.getString(3));
    				con1.setContact1(rs.getString(4));
    				con1.setRemarks1(rs.getString(5));
    				con1.setUnit1(rs.getString(6));
    			
    				a.add(con1);
    			}
    			
    			rs.close();
    			stmt.close();
    			con.close();
    		} catch (Exception e) {
    			e.printStackTrace();
    		}
    		request.setAttribute("empmaster", a);
    		
		}
		return mapping.findForward("display");
	}
}