/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.AccountantReportForm;
import com.forms.ReportsForm;

public class AccountantReportAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountantReportForm accountantReportForm = (AccountantReportForm) form;// TODO Auto-generated method stub
		
		System.out .println("control in display");
		HttpSession session = request.getSession();

		 String com=(String) session.getAttribute("companyname");
			 
		 accountantReportForm.setUnit(com);
		return mapping.findForward("display");
	}
	
	
	public ActionForward show4(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountantReportForm reports = (AccountantReportForm) form;// TODO Auto-generated method stub
		String fromdate = reports.getFromdate();
		String todate = reports.getTodate();

		HttpSession session = request.getSession();

		 String com=(String) session.getAttribute("companyname"); 
		 String str = reports.getReport();
		Connection con = DBUtil.openConnection();
		ResultSet rs = null;
		Statement stmt = null;
		String  reportQuerry="";
		String  reportFname="";
		if (str.equalsIgnoreCase("AdminAccount")) {  

			 reportQuerry = "SELECT * FROM ADMINACCOUNT WHERE  DATEOF BETWEEN TO_DATE('"+fromdate+"','DD/MM/YYYY') AND TO_DATE('"+todate+"','DD/MM/YYYY')  AND UNIT = '"+com+"' ORDER BY ID ASC";
			System.out.println("report query "+reportQuerry);
		    reportFname="admin.rpt";
			reports.setReportShow("YES");
			session.setAttribute("query", reportQuerry);
			session.setAttribute("report", reportFname);
			session.setAttribute("showRep", "showRep");

			return mapping.findForward("display");

		}
		else if (str.equalsIgnoreCase("Accountant"))
		  {
			
			reportQuerry = "SELECT * FROM ACCOUNTANT WHERE   DATEOF BETWEEN TO_DATE('"+fromdate+"','DD/MM/YYYY') AND TO_DATE('"+todate+"','DD/MM/YYYY')  AND UNIT = '"+com+"' ORDER BY ID ASC";
			System.out.println("report query "+reportQuerry);
		    reportFname="accountant.rpt";
			reports.setReportShow("YES");
			session.setAttribute("query", reportQuerry);
			session.setAttribute("report", reportFname);
			session.setAttribute("showRep", "showRep");
			return mapping.findForward("display");
			}
			else {

				reportQuerry = "SELECT * FROM CLIENTPAYMENT WHERE  DATEOFPAY BETWEEN TO_DATE('"+fromdate+"','DD/MM/YYYY') AND TO_DATE('"+todate+"','DD/MM/YYYY') AND UNIT = '"+com+"' ORDER BY ID ASC";
				System.out.println("report query "+reportQuerry);
			    reportFname="client1.rpt";
				reports.setReportShow("YES");
				session.setAttribute("query", reportQuerry);
				session.setAttribute("report", reportFname);
				session.setAttribute("showRep", "showRep");
				return mapping.findForward("display");
			}
}
}