/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.forms.AccountanthistoryForm;
import com.forms.ContactHistoryForm;

public class AccountanthistoryAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountanthistoryForm contactHistoryForm = (AccountanthistoryForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();

		 String com=(String) session.getAttribute("companyname");
			 
		 contactHistoryForm.setUnit(com);
		return mapping.findForward("display");
	}
	
	

	public ActionForward filterName(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountanthistoryForm contactHistoryForm = (AccountanthistoryForm) form;// TODO Auto-generated method stub
	
		
		return mapping.findForward("display1");
	}
	
	public ActionForward filterNumber(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountanthistoryForm contactHistoryForm = (AccountanthistoryForm) form;// TODO Auto-generated method stub
	
		return mapping.findForward("display2");
	}
}