/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.forms.AccountForm;
import com.forms.AccountsForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-22-2016
 * 
 * XDoclet definition:
 * @struts.action path="/account" name="accountForm" input="/jsp/account.jsp" parameter="method" scope="request" validate="true"
 */
public class AccountAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountForm accounts = (AccountForm) form;// TODO Auto-generated method stub
		return mapping.findForward("display");
	}
	public ActionForward accountant(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountForm accounts = (AccountForm) form;// TODO Auto-generated method stub
		
		System.out.println("coming here........");
		String type=accounts.getType();
		
			
		return mapping.findForward("slno");
		
	}
	public ActionForward accountant1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountForm accounts = (AccountForm) form;// TODO Auto-generated method stub
		
		System.out.println("coming here........");
		
		return mapping.findForward("accountant1234");
		
	}
}