/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.forms.BankDetailsForm;


public class BankDetailsAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BankDetailsForm bankDetailsForm = (BankDetailsForm) form;// TODO Auto-generated method stub
		return mapping.findForward("display");
	}
	public ActionForward displayC(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BankDetailsForm bankDetailsForm = (BankDetailsForm) form;// TODO Auto-generated method stub
		return mapping.findForward("displaycomp");
	}
	public ActionForward displayE(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BankDetailsForm bankDetailsForm = (BankDetailsForm) form;// TODO Auto-generated method stub
		return mapping.findForward("displayemp");
	}
	
	
}