/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.AccountHistoryForm;
import com.forms.AdminaccountForm;
import com.forms.ContactHistoryForm;


public class ContactHistoryAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ContactHistoryForm contactHistoryForm = (ContactHistoryForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		System.out .println("control in display");
		 String com=(String) session.getAttribute("companyname"); 
		 contactHistoryForm.setUnit(com);
		return mapping.findForward("display");
	}
	
	

	public ActionForward filterName(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ContactHistoryForm contactHistoryForm = (ContactHistoryForm) form;// TODO Auto-generated method stub
	
		
		return mapping.findForward("display1");
	}
	
	public ActionForward filterNumber(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ContactHistoryForm contactHistoryForm = (ContactHistoryForm) form;// TODO Auto-generated method stub
	
		return mapping.findForward("display2");
	}
	
	
	
}