/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.ContactManageForm;


public class ContactManageAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		ContactManageForm contactManageForm = (ContactManageForm) form;// TODO Auto-generated method stub
		
		Connection con = DBUtil.openConnection();
		Statement stmt = con.createStatement();
		ResultSet rs=null;
		HttpSession session = request.getSession();

		 String com=(String) session.getAttribute("companyname");
			 
		 contactManageForm.setUnit(com);
		
		

		if(com.equalsIgnoreCase("IngroInfo Software Solutions pvt ltd."))
        { 
			String Sql = "SELECT * FROM CONTACT_MANAGEMENT WHERE SLNO LIKE '%_IGI%' ORDER BY SLNO ASC";
			rs = stmt.executeQuery(Sql);
			

		int count = 1;
		int count1 = 1;
		while (rs.next()) {
			 String oldVersion = rs.getString("SLNO");
			 String version = oldVersion; 
			 System.out.println("string"+version);	
				count++;
		    String[] splitString = version.split("-");
		    System.out.println("String is"+splitString[0]);
		    System.out.println("int"+splitString[1]);
		   /*String[] split = splitString[0].split("~"); 
		    System.out.println("String is"+split);*/

		    //int newVersion = Integer.valueOf(splitString[1])+1;
		    count1=count;
		}
           int newVersion = count1++;
		 String completeNewVersion = "Admin_IGI-" + newVersion;
		    System.out.print(completeNewVersion);
		    contactManageForm.setSlno(completeNewVersion);
        }
        else {
        	String Sql = "SELECT * FROM CONTACT_MANAGEMENT WHERE SLNO LIKE '%_RK%' ORDER BY SLNO ASC";
			rs = stmt.executeQuery(Sql);
    		int count = 1;
    		int count1 = 1;
    		while (rs.next()) {
    			 String oldVersion = rs.getString("SLNO");
    			 String version = oldVersion; 
    			 System.out.println("string"+version);
    		 
    				
    				count++;
    		    String[] splitString = version.split("-");
    		    System.out.println("String is"+splitString[0]);
    		    System.out.println("int"+splitString[1]);
    		   /*String[] split = splitString[0].split("~"); 
    		    System.out.println("String is"+split);*/

    		    //int newVersion = Integer.valueOf(splitString[1])+1;
    		    count1=count;
    		}
               int newVersion = count1++;
    		 String completeNewVersion = "Admin_RK-" + newVersion;
    		    System.out.print(completeNewVersion);
    		    contactManageForm.setSlno(completeNewVersion);
		}
	    DBUtil.closeStatement(stmt);
		DBUtil.closeConnection(con);
	    
		return mapping.findForward("display");
	}
	
	
	public ActionForward submitDetails(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		ContactManageForm contactManageForm = (ContactManageForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();

	String slno = contactManageForm.getSlno();
	String name = contactManageForm.getName();
	String place = contactManageForm.getPlace();
	String contact = contactManageForm.getContact();
	String remarks = contactManageForm.getRemarks();
	String company=contactManageForm.getUnit();
	
	
	System.out.println("slno "+slno+" Name is "+name+" place is "+place+" contact number is "+contact+" remarks "+remarks+" company name is"+company);
	
	Connection con = DBUtil.openConnection();
	Statement stmt = con.createStatement();
	ResultSet rs=null;
	String Sql1 = "SELECT * FROM CONTACT_MANAGEMENT ORDER BY ID ASC";
	rs = stmt.executeQuery(Sql1);
	int count2 = 1;
	int count3 = 1;
	while (rs.next()) {
		 String oldVersion = rs.getString("ID");
		 String version = oldVersion; 
		 System.out.println("string"+version);
	 
			
			count2++;
			 count3=count2;
			 
	}
	int num = count3++;
	
    System.out.print(num);
    
	String sql = "INSERT INTO CONTACT_MANAGEMENT VALUES('"+slno+"','"+name+"','"+place+"','"+contact+"','"+remarks+"','"+company+"','"+num+"')";
	stmt.executeUpdate(sql);
	
	
	
	request.setAttribute("msg"," data inserted successfully ");
	 String com=(String) session.getAttribute("companyname");

	

	if(com.equalsIgnoreCase("IngroInfo Software Solutions pvt ltd."))
    { 
		String Sql = "SELECT * FROM CONTACT_MANAGEMENT WHERE SLNO LIKE '%_IGI%' ORDER BY SLNO ASC";
		rs = stmt.executeQuery(Sql);
	int count = 1;
	int count1 = 1;
	while (rs.next()) {
		 String oldVersion = rs.getString("SLNO");
		 String version = oldVersion; 
		 System.out.println("string"+version);	
			count++;
	    String[] splitString = version.split("-");
	    System.out.println("String is"+splitString[0]);
	    System.out.println("int"+splitString[1]);
	   /*String[] split = splitString[0].split("~"); 
	    System.out.println("String is"+split);*/

	    //int newVersion = Integer.valueOf(splitString[1])+1;
	    count1=count;
	}
       int newVersion = count1++;
	 String completeNewVersion = "Admin_IGI-" + newVersion;
	    System.out.print(completeNewVersion);
	    contactManageForm.setSlno(completeNewVersion);
    }
    else {
    	String Sql = "SELECT * FROM CONTACT_MANAGEMENT WHERE SLNO LIKE '%_RK%' ORDER BY SLNO ASC";
		rs = stmt.executeQuery(Sql);
		int count = 1;
		int count1 = 1;
		while (rs.next()) {
			 String oldVersion = rs.getString("SLNO");
			 String version = oldVersion; 
			 System.out.println("string"+version);
		 
				
				count++;
		    String[] splitString = version.split("-");
		    System.out.println("String is"+splitString[0]);
		    System.out.println("int"+splitString[1]);
		   /*String[] split = splitString[0].split("~"); 
		    System.out.println("String is"+split);*/

		    //int newVersion = Integer.valueOf(splitString[1])+1;
		    count1=count;
		}
           int newVersion = count1++;
		 String completeNewVersion = "Admin_RK-" + newVersion;
		    System.out.print(completeNewVersion);
		    contactManageForm.setSlno(completeNewVersion);
	}
    
    contactManageForm.setName("");
	contactManageForm.setPlace("");
	contactManageForm.setContact("");
	contactManageForm.setRemarks("");
	
    DBUtil.closeStatement(stmt);
	DBUtil.closeConnection(con);
	
	
	return mapping.findForward("display");
}	
	
	
}