/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.DevtimeForm;
import com.forms.WorkingtimeForm;

public class DevtimeAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		DevtimeForm devtimeForm = (DevtimeForm) form;// TODO Auto-generated method stub
	HttpSession session = request.getSession();
	String com=(String) session.getAttribute("companyname");
	ArrayList al =(ArrayList)session.getAttribute("empDetails");
	Connection con = DBUtil.openConnection();
	String username = (String)al.get(1);
	devtimeForm.setUser(username);
	devtimeForm.setUser1(username);
	String user = devtimeForm.getUser();
	DateFormat dateFormat3 = new SimpleDateFormat("dd/MM/yyyy");
	Date date3 = new Date();
	String str3 = dateFormat3.format(date3);
	   /*   DateFormat dateFormat3 = new SimpleDateFormat("dd/MM/yyyy");
	 
	      Calendar cal = Calendar.getInstance();
	       cal.add(Calendar.DATE, -1);
	       
	        String ydate =  dateFormat3.format(cal.getTime());
	        System.out.println("YESTERDAY DATE "+ydate);*/
	String ab = "SELECT * FROM EMPLOYEES WHERE UNIT = '"+com+"' ";
	Statement abs = con.createStatement();
	ResultSet abr = abs.executeQuery(ab);
	while(abr.next())
	{
		String id = abr.getString("EMP_ID");
		System.out.println("id is "+id);
		String name = abr.getString("USERNAME");
		System.out.println("name is "+name);
		String pr = "SELECT * FROM WORKTIME WHERE EMPID IS NOT NULL AND EMPID = '"+id+"' AND CURRENTDATE = TO_DATE('"+str3+"','DD/MM/YYYY') and unit = '"+com+"'";
		Statement prs = con.createStatement();
		//int pd = prs.executeUpdate(pr);
		ResultSet prr = prs.executeQuery(pr);
		System.out.println("prr query is "+pr);
		if(prr.next())
		{
			System.out.println("aaaaaaaaaaaaa");
			
		}
		else {
			System.out.println("bbbbbbbbbbb");
			String pa = "INSERT INTO   WORKTIME (PRESENT_ABSENT,USERNAME,CURRENTDATE,UNIT,EMPID,TOTALTIME,CURRENTMONTH)  VALUES ('Absent','"+name+"', TO_DATE('"+str3+"','DD/MM/YYYY'),'"+com+"','"+id+"','','')";
			Statement paa = con.createStatement();
			int pas = paa.executeUpdate(pa);
			System.out.println("pas query is "+pa);
		}
	}
	
	String name = (String) session.getAttribute("userName");
	String password = (String) session.getAttribute("password");
	
	DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
    
	Date date = new Date();
	String str = dateFormat.format(date);
	devtimeForm.setStarttime(str);
	devtimeForm.setTotime(str);
	
	
	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	String str2 = "SELECT EMP_ID FROM EMPLOYEES WHERE USERNAME = '"+name+"' AND PASS_WORD = '"+password+"' AND UNIT = '"+com+"' ORDER BY USERNAME ASC";
	 ResultSet rs1 = stmt1.executeQuery(str2);
	 System.out.println("rs is"+rs1);
	 if (rs1.next()) {
		 
		 devtimeForm.setEmpid(rs1.getString("EMP_ID"));
	}

     String id = devtimeForm.getEmpid();
	 System.out.println("id is"+id);


	DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
	Date date1 = new Date();
	String str1 = dateFormat1.format(date1);
	String sql1 = "SELECT * FROM WORKTIME WHERE TOTIME IS NOT  NULL AND EMPID = '"+id+"' AND UNIT ='"+com+"'  AND STARTTIME IS NOT NULL AND CURRENTDATE = TO_DATE('"+str1+"','DD/MM/YYYY')  ";
	int t = stmt1.executeUpdate(sql1);
	System.out.println("===========================");
	System.out.println("t value is"+t);
	if(t>0) {
		System.out.println("123456");
         devtimeForm.setStarttime("");
		devtimeForm.setTotime("");
	

	

	
}
	else{
		devtimeForm.setTotime(str);
	

	 
	}
	String sql3 = "SELECT * FROM WORKTIME WHERE STARTTIME IS NOT NULL AND UNIT = '"+com+"' AND EMPID ='"+id+"' AND CURRENTDATE = TO_DATE('"+str1+"','DD/MM/YYYY') ";
	int P = stmt1.executeUpdate(sql3);
	System.out.println("===========================");
	System.out.println("t value is"+t);
	if(P>0) {
		System.out.println("123456");
         
		devtimeForm.setStarttime("");
	
			
	

	
}
	else{
		devtimeForm.setStarttime(str);

	
	}
	return mapping.findForward("display"); 
}

public ActionForward sendwork(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) throws SQLException {
	DevtimeForm workingtimeForm = (DevtimeForm) form;// TODO Auto-generated method stub
	HttpSession session = request.getSession();
	System.out .println("control in display");
	 String com=(String) session.getAttribute("companyname"); 

		DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
		Date date1 = new Date();
		String str = dateFormat1.format(date1);
		DateFormat dateFormat2 = new SimpleDateFormat("MM");
		Date date2 = new Date();
		String month = dateFormat2.format(date2);
		System.out.println("month is "+month);
	String starttime = workingtimeForm.getStarttime();
	String user = workingtimeForm.getUser();
	Connection con = DBUtil.openConnection();
	Statement stmt = con.createStatement();
	Statement stmt1 = con.createStatement();
	String name = (String) session.getAttribute("userName");
	String password = (String) session.getAttribute("password");
	String str1 = "SELECT EMP_ID FROM EMPLOYEES WHERE USERNAME = '"+name+"' AND PASS_WORD = '"+password+"' AND UNIT = '"+com+"' ORDER BY USERNAME ASC";
	 ResultSet rs = stmt1.executeQuery(str1);
	 System.out.println("rs is"+rs);
	 if (rs.next()) {
		 
		workingtimeForm.setEmpid(rs.getString("EMP_ID"));
	}

   String id = workingtimeForm.getEmpid();
	 System.out.println("id is"+id);

	String sql1 = "SELECT * FROM WORKTIME WHERE STARTTIME IS NOT NULL AND EMPID = '"+id+"' AND UNIT ='"+com+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY')";
	int t = stmt1.executeUpdate(sql1);
	System.out.println("===========================");
	System.out.println("t value is"+t);
	if(t>0) {
		System.out.println("123456");

		 workingtimeForm.setStarttime("");
			return mapping.findForward("display");
	

	
}
	 else {
		
		 System.out.println("--------------"); 
	       String sql = "UPDATE WORKTIME SET STARTTIME = '"+starttime+"',CURRENTMONTH  = '"+month+"' WHERE EMPID = '"+id+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY')"; 

		// String sql = "INSERT INTO   WORKTIME  (STARTTIME,USERNAME,CURRENTDATE,UNIT,EMPID,CURRENTMONTH) VALUES ('"+starttime+"','"+user+"',TO_DATE('"+str+"','DD/MM/YYYY'),'"+com+"','"+id+"','"+month+"')";
			stmt.executeUpdate(sql);

        	  System.out.println("00000000000");
			  request.setAttribute("msg"," data inserted successfully");
		workingtimeForm.setStarttime("");
		return mapping.findForward("display");
	}
}
public ActionForward senddetails(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) throws SQLException, ParseException {
	DevtimeForm workingtimeForm = (DevtimeForm) form;// TODO Auto-generated method stub
	String totime = workingtimeForm.getTotime();
	String user = workingtimeForm.getUser1();
	Connection con = DBUtil.openConnection();
	HttpSession session = request.getSession();
	 String com=(String) session.getAttribute("companyname"); 
	 String name = (String) session.getAttribute("userName");
		String password = (String) session.getAttribute("password");
    String stime = "";
	DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
	Date date1 = new Date();
	String str = dateFormat1.format(date1);
	DateFormat dateFormat2 = new SimpleDateFormat("MM");
	Date date2 = new Date();
	String month = dateFormat2.format(date2);
	System.out.println("month is "+month);
	ResultSet rs = null;
	Statement stmt = con.createStatement();
	 System.out.println("--------------"); 
		Statement stmt1 = con.createStatement();
		String str1 = "SELECT EMP_ID FROM EMPLOYEES WHERE USERNAME = '"+name+"' AND PASS_WORD = '"+password+"' AND UNIT = '"+com+"' ORDER BY USERNAME ASC";
		 ResultSet rs1 = stmt1.executeQuery(str1);
		 System.out.println("rs is"+rs);
		 if (rs1.next()) {
		workingtimeForm.setEmpid(rs1.getString("EMP_ID"));
		}

          String id = workingtimeForm.getEmpid();
 		 System.out.println("id is"+id);
		
		String sql1 = "SELECT * FROM WORKTIME WHERE TOTIME IS NOT NULL AND EMPID = '"+id+"' AND UNIT = '"+com+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY')";
		int t = stmt1.executeUpdate(sql1);
		System.out.println("===========================");
		System.out.println("t value is"+t);
		if(t>0) {
			System.out.println("123456");

			 workingtimeForm.setTotime("");
				return mapping.findForward("display");
		

		
	}else {
		
	
		String sql2 = "SELECT STARTTIME FROM  WORKTIME WHERE STARTTIME IS NOT NULL AND EMPID = '"+id+"' AND UNIT = '"+com+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY')";
		ResultSet rs3 = stmt.executeQuery(sql2);
		
		if (rs3.next()) {
			 stime = rs3.getString("STARTTIME");

		System.out.println("starttime is  "+stime);
		}
		
		String st = stime;
		String tt = totime;
		  SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");

		  Date d1 = null;
		  Date d2 = null;

		
		   d1 = format.parse(st);
		   d2 = format.parse(tt);

		   //in milliseconds
		   long diff = d2.getTime() - d1.getTime();
		   System.out.println(diff);
		   long diffSeconds = diff / 1000 % 60;
		   long diffMinutes = diff / (60 * 1000) % 60;
		   long diffHours = diff / (60 * 60 * 1000) % 24;
		   long diffDays = diff / (24 * 60 * 60 * 1000);

		   
		  String time=diffHours + ":"+diffMinutes+":"+diffSeconds;
		  System.out.println(time);
       String sql = "UPDATE WORKTIME SET STARTTIME = '"+stime+"', TOTIME = '"+totime+"',TOTALTIME='"+time+"',PRESENT_ABSENT ='Present' WHERE EMPID = '"+id+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY')"; 
	// String sql = "INSERT INTO   WORKTIME (STARTTIME,TOTIME,USERNAME,CURRENTDATE,UNIT,EMPID,TOTALTIME,CURRENTMONTH)  VALUES ('"+stime+"','"+totime+"','"+user+"', TO_DATE('"+str+"','DD/MM/YYYY'),'"+com+"','"+id+"','"+time+"','"+month+"')";
		stmt.executeUpdate(sql);
       	  System.out.println("00000000000");
       	  workingtimeForm.setTotime("");
		  request.setAttribute("msg"," data inserted successfully");
	return mapping.findForward("display");
}

}

public ActionForward view(ActionMapping mapping, ActionForm form, 
		HttpServletRequest request, HttpServletResponse response) throws SQLException {
	DevtimeForm workingtimeForm = (DevtimeForm) form;// TODO Auto-generated method stub
	HttpSession session = request.getSession();
	 String com=(String) session.getAttribute("companyname"); 	
	 DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
	Date date1 = new Date();
	String str = dateFormat1.format(date1);
	String user1 = workingtimeForm.getUser();

	Connection con = DBUtil.openConnection();
	ResultSet rs = null;
	ResultSet rs1 = null;
	Statement stmt = null;
	Statement stmt1 = null;
	String name = (String) session.getAttribute("userName");
	String password = (String) session.getAttribute("password");
	String str1 = "SELECT EMP_ID FROM EMPLOYEES WHERE USERNAME = '"+name+"' AND PASS_WORD = '"+password+"' AND UNIT = '"+com+"' ORDER BY USERNAME ASC";
	stmt1 = con.createStatement();

	ResultSet r1 = stmt1.executeQuery(str1);
	 System.out.println("rs is"+rs);
	 if (r1.next()) {
		 
		workingtimeForm.setEmpid(r1.getString("EMP_ID"));
	}

   String id = workingtimeForm.getEmpid();
	 System.out.println("id is"+id);
	String Sql = "SELECT STARTTIME FROM WORKTIME WHERE EMPID = '"+id+"' AND UNIT ='"+com+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY') ORDER BY STARTTIME ASC" ;
	ArrayList a = new ArrayList();
	WorkingtimeForm wf = null;
	stmt = con.createStatement();
	rs = stmt.executeQuery(Sql);
	
	if(rs.next()) {
		wf = new WorkingtimeForm();
		wf.setStime(rs.getString("STARTTIME"));
		
		String Sql1 = "SELECT TOTIME FROM WORKTIME WHERE EMPID = '"+id+"'  AND UNIT ='"+com+"' AND CURRENTDATE = TO_DATE('"+str+"','DD/MM/YYYY') ORDER BY TOTIME ASC" ;
		stmt1 = con.createStatement();
		rs1 = stmt1.executeQuery(Sql1);
        if (rs1.next()) {
			wf.setName(rs1.getString("TOTIME"));
		}

        a.add(wf);
	}
	
	rs.close();
	stmt.close();
	con.close();
	request.setAttribute("displaymanag", a);
	return mapping.findForward("display");  
}
} 