/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.ContactHistoryForm;
import com.forms.DisplayworkForm;


public class DisplayworkAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DisplayworkForm displayworkForm = (DisplayworkForm) form;
		HttpSession session = request.getSession();

		return mapping.findForward("display");
	}
	
	/*public ActionForward displayrecords(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DisplayworkForm cf1 = (DisplayworkForm) form;// TODO Auto-generated method stub
		System.out.println("inside action class");
		Connection con = DBUtil.openConnection();
		HttpSession session = request.getSession();
		String str = (String) session.getAttribute("companyname");
		System.out.println("string is"+str);
		cf1.setUnit(str);

		System.out.println("connection------"+con);
	     try { 
	     Statement stmt = (Statement) con.createStatement();
	      
	        String sql = "SELECT USERNAME FROM EMPLOYEES WHERE UNIT = '"+str+"' ORDER BY USERNAME ASC";
	       
	       System.out.println("=====");
	        ResultSet rs = stmt.executeQuery(sql);
	        ArrayList<String> List1 = new ArrayList<String>();
	        while (rs.next()) {

	            List1.add(rs.getString("USERNAME"));
	            
	      }
	        System.out.println("------------");
	        if( List1!=null){
	         System.out.println("inside if");
	         session.setAttribute("plist",  List1);
	      return mapping.findForward("display");
	      
	        }
	     }catch(Exception e){
	      e.printStackTrace();
	     } 
	     
	 
		return mapping.findForward("display");
	}
	*/
	public ActionForward showhistory(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		DisplayworkForm displayworkForm = (DisplayworkForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();

		 String com=(String) session.getAttribute("companyname"); 
		 String query = (String)request.getParameter("name");

			System.out.println("name="+query);

		Connection con = DBUtil.openConnection();
		ResultSet rs = null; 
		Statement stmt = null;
		if (query.equalsIgnoreCase("All")) {
			String sql1 ="SELECT * FROM DAILYWORKDETAILS WHERE UNIT ='"+com+"'";
			ArrayList a1 = new ArrayList();

			try {
				stmt = con.createStatement();
				rs = stmt.executeQuery(sql1); 
				DisplayworkForm ds1 = null;
				
				while (rs.next()) {
					ds1 = new DisplayworkForm();
					ds1.setFromtime1(rs.getString("FROMTIME"));
					ds1.setTotime1(rs.getString("TOTIME"));
ds1.setWork(rs.getString("WORKDETAILS"));
					ds1.setStatus(rs.getString("STATUS"));
					ds1.setUsername1(rs.getString("USERNAME"));
					ds1.setDate(rs.getString("DATE"));

					a1.add(ds1);
					
				}
	   			
	   			rs.close();
	   			stmt.close();
	   			con.close();
	   		} catch (Exception e) {
	   			e.printStackTrace();
	   		}
	   		request.setAttribute("empmaster", a1);
	   		
			}
				else {
					
		String sql ="SELECT * FROM DAILYWORKDETAILS WHERE UPPER(USERNAME) like '%' || UPPER('"+query+"') || '%' AND UNIT = '"+com+"'";
		ArrayList a = new ArrayList();
		try {
	
			stmt = con.createStatement();
			rs = stmt.executeQuery(sql); 
			DisplayworkForm ds = null;
			while (rs.next()) {
				ds = new DisplayworkForm();
				ds.setFromtime1(rs.getString("FROMTIME"));
				ds.setTotime1(rs.getString("TOTIME"));
				ds.setWork(rs.getString("WORKDETAILS"));
				ds.setStatus(rs.getString("STATUS"));
				ds.setUsername1(rs.getString("USERNAME"));
				ds.setDate(rs.getString("DATE"));

				a.add(ds);
			}
				rs.close();
	   			stmt.close();
	   			con.close();
	   		} catch (Exception e) {
	   			e.printStackTrace();
	   		}
	   		request.setAttribute("empmaster", a);
	   		
			}
			
			 
			return mapping.findForward("display");
	}
	
	
	
}
