/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dbUtil.DBUtil;
import com.forms.ClientHistoryForm;
import com.forms.PersonalhistoryForm;

public class PersonalhistoryAction extends DispatchAction {
	
	public ActionForward display(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PersonalhistoryForm personalhistoryForm = (PersonalhistoryForm) form;// TODO Auto-generated method stub
		return mapping.findForward("display");
	}

	public ActionForward personaldisplay(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PersonalhistoryForm personalhistoryForm = (PersonalhistoryForm) form;
		
		String fromdate=personalhistoryForm.getFromdate(); 
		String todate=personalhistoryForm.getTodate();
		HttpSession session = request.getSession();
		 String com=(String) session.getAttribute("companyname"); 
		 Connection con = DBUtil.openConnection();
			ResultSet rs = null;
			Statement stmt = null;
			String Sql = "SELECT * FROM PERSONAL_DETAILS WHERE   DATEOFENTRY BETWEEN TO_DATE('"+fromdate+"','DD/MM/YYYY') AND TO_DATE('"+todate+"','DD/MM/YYYY') AND UNIT = '"+com+"' ORDER BY ID ASC";
			ArrayList a = new ArrayList();
			
			try {
				stmt = con.createStatement();
				rs = stmt.executeQuery(Sql);
				while (rs.next()) {
					PersonalhistoryForm cl=new PersonalhistoryForm();
					cl.setSlno(rs.getString(1));
					cl.setDate1(rs.getString(2));
					cl.setDesc(rs.getString(3));
					cl.setAmount(rs.getInt(4));
					cl.setRemark(rs.getString(5));
					cl.setCredit(rs.getInt(6));
					
					a.add(cl);
				}
				rs.close();
				stmt.close();
				con.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
			request.setAttribute("empmaster", a);
			
		return mapping.findForward("display");
	
	}		
}