/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class AccountantForm extends ActionForm {

	private static final long serialVersionUID = 1L;
	private String slno;
	private String date;
	private String particulars;
	private String invoice;
	private String for1;
	private String amount;
	private String credit;
	private String remarks;
	private String userNameData;
	private String passwordData;
	private String message;
	private int total;
	private String year1;
	private Date date2;

	public Date getDate2() {
		return date2;
	}

	public void setDate2(Date date2) {
		this.date2 = date2;
	}

	public String getYear1() {
		return year1;
	}

	public void setYear1(String year1) {
		this.year1 = year1;
	}

	private String companyname;

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	private String slno1;
	private String date1;
	private String particulars1;
	private String invoice1;
	private String for12;
	private String amount1;
	private String credit1;
	private String remarks1;

	private String year;
	private String account;

	private String unit;
	private String unit1;

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getUnit1() {
		return unit1;
	}

	public void setUnit1(String unit1) {
		this.unit1 = unit1;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getSlno1() {
		return slno1;
	}

	public void setSlno1(String slno1) {
		this.slno1 = slno1;
	}

	public String getDate1() {
		return date1;
	}

	public void setDate1(String date1) {
		this.date1 = date1;
	}

	public String getParticulars1() {
		return particulars1;
	}

	public void setParticulars1(String particulars1) {
		this.particulars1 = particulars1;
	}

	public String getInvoice1() {
		return invoice1;
	}

	public void setInvoice1(String invoice1) {
		this.invoice1 = invoice1;
	}

	public String getFor12() {
		return for12;
	}

	public void setFor12(String for12) {
		this.for12 = for12;
	}

	public String getAmount1() {
		return amount1;
	}

	public void setAmount1(String amount1) {
		this.amount1 = amount1;
	}

	public String getCredit1() {
		return credit1;
	}

	public void setCredit1(String credit1) {
		this.credit1 = credit1;
	}

	public String getRemarks1() {
		return remarks1;
	}

	public void setRemarks1(String remarks1) {
		this.remarks1 = remarks1;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getTotal() {
		return total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPasswordData() {
		return passwordData;
	}

	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}

	public String getUserNameData() {
		return userNameData;
	}

	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}

	public String getSlno() {
		return slno;
	}

	public void setSlno(String slno) {
		this.slno = slno;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getParticulars() {
		return particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	public String getInvoice() {
		return invoice;
	}

	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}

	public String getFor1() {
		return for1;
	}

	public void setFor1(String for1) {
		this.for1 = for1;
	}

	public String getAmount() {
		return amount;
	}

	public void setAmount(String string) {
		this.amount = string;
	}

	public String getCredit() {
		return credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}