/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class ClientHistoryForm extends ActionForm {
	
	private String unit;
	private String year;
	private String fromdate;
	private String todate;
	private String userNameData;
	private String passwordData;
	private String message;
	private String slno121;
	private String date121;
	private String project1;
	private String invoice121;
	private String invoice1;
	private String amount121;
	private String type1;
	private String companyname;
	private String type;
	private String name;
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	private String year1;
	private String accnumber1;
	
	public String getAccnumber1() {
		return accnumber1;
	}
	public void setAccnumber1(String accnumber1) {
		this.accnumber1 = accnumber1;
	}
	public String getYear1() {
		return year1;
	}
	public void setYear1(String year1) {
		this.year1 = year1;
	}
	public String getSlno121() {
		return slno121;
	}
	public void setSlno121(String slno121) {
		this.slno121 = slno121;
	}
	public String getDate121() {
		return date121;
	}
	public void setDate121(String date121) {
		this.date121 = date121;
	}
	public String getProject1() {
		return project1;
	}
	public void setProject1(String project1) {
		this.project1 = project1;
	}
	public String getInvoice121() {
		return invoice121;
	}
	public void setInvoice121(String invoice121) {
		this.invoice121 = invoice121;
	}
	public String getInvoice1() {
		return invoice1;
	}
	public void setInvoice1(String invoice1) {
		this.invoice1 = invoice1;
	}
	public String getAmount121() {
		return amount121;
	}
	public void setAmount121(String amount121) {
		this.amount121 = amount121;
	}
	public String getType1() {
		return type1;
	}
	public void setType1(String type1) {
		this.type1 = type1;
	}
	public String getUnit1() {
		return unit1;
	}
	public void setUnit1(String unit1) {
		this.unit1 = unit1;
	}
	public String getUnit2() {
		return unit2;
	}
	public void setUnit2(String unit2) {
		this.unit2 = unit2;
	}
	private String unit1;
	private String unit2;
	
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getYear() {
		return year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public String getFromdate() {
		return fromdate;
	}
	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}
	public String getTodate() {
		return todate;
	}
	public void setTodate(String todate) {
		this.todate = todate;
	}
	
	
}