/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import java.util.Date;

import org.apache.struts.action.ActionForm;

public class DashboardForm extends ActionForm {
	private static final long serialVersionUID = 1L;
	private String complaintNo;
	private int totalCopen;
	private int pending;
	private int done;
	private String complEscalate;
	private int complaintNH;
	private int complaintReg;
	private String complNo;
	private String complaintDate;
	private String jobCardGenerateDate;
	private String complAttnDate;
	private String complAttnRem;
	private String closedDate;
	private String feedback;
	private Date date;
	private Date date1;
	private Date date2;
	private String companyname;
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	private Date date3;
	private int escCount;
	private int totalCount;
	private String funcBussDept;
	private String userNameData;
	private String passwordData;
	public String getComplaintNo() {
		return complaintNo;
	}
	public void setComplaintNo(String complaintNo) {
		this.complaintNo = complaintNo;
	}
	public int getTotalCopen() {
		return totalCopen;
	}
	public void setTotalCopen(int totalCopen) {
		this.totalCopen = totalCopen;
	}
	public int getPending() {
		return pending;
	}
	public void setPending(int pending) {
		this.pending = pending;
	}
	public int getDone() {
		return done;
	}
	public void setDone(int done) {
		this.done = done;
	}
	public String getComplEscalate() {
		return complEscalate;
	}
	public void setComplEscalate(String complEscalate) {
		this.complEscalate = complEscalate;
	}
	public int getComplaintNH() {
		return complaintNH;
	}
	public void setComplaintNH(int complaintNH) {
		this.complaintNH = complaintNH;
	}
	public int getComplaintReg() {
		return complaintReg;
	}
	public void setComplaintReg(int complaintReg) {
		this.complaintReg = complaintReg;
	}
	public String getComplNo() {
		return complNo;
	}
	public void setComplNo(String complNo) {
		this.complNo = complNo;
	}
	public String getComplaintDate() {
		return complaintDate;
	}
	public void setComplaintDate(String complaintDate) {
		this.complaintDate = complaintDate;
	}
	public String getJobCardGenerateDate() {
		return jobCardGenerateDate;
	}
	public void setJobCardGenerateDate(String jobCardGenerateDate) {
		this.jobCardGenerateDate = jobCardGenerateDate;
	}
	public String getComplAttnDate() {
		return complAttnDate;
	}
	public void setComplAttnDate(String complAttnDate) {
		this.complAttnDate = complAttnDate;
	}
	public String getComplAttnRem() {
		return complAttnRem;
	}
	public void setComplAttnRem(String complAttnRem) {
		this.complAttnRem = complAttnRem;
	}
	public String getClosedDate() {
		return closedDate;
	}
	public void setClosedDate(String closedDate) {
		this.closedDate = closedDate;
	}
	public String getFeedback() {
		return feedback;
	}
	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public Date getDate1() {
		return date1;
	}
	public void setDate1(Date date1) {
		this.date1 = date1;
	}
	public Date getDate2() {
		return date2;
	}
	public void setDate2(Date date2) {
		this.date2 = date2;
	}
	public Date getDate3() {
		return date3;
	}
	public void setDate3(Date date3) {
		this.date3 = date3;
	}
	public int getEscCount() {
		return escCount;
	}
	public void setEscCount(int escCount) {
		this.escCount = escCount;
	}
	public int getTotalCount() {
		return totalCount;
	}
	public void setTotalCount(int totalCount) {
		this.totalCount = totalCount;
	}
	public String getFuncBussDept() {
		return funcBussDept;
	}
	public void setFuncBussDept(String funcBussDept) {
		this.funcBussDept = funcBussDept;
	}
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}