/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-01-2016
 * 
 * XDoclet definition:
 * @struts.form name="fieldtenderForm"
 */
public class FieldtenderForm extends ActionForm {
}