/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

public class Fieldtender1Form extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String sernum;
	private String datepick;
	private String tenderNumber;
	private String tender;
	private String calldat;
	private String lastdat;
	private String employ;
	private FormFile file;
	private String user;
	private String message;
	private String unit;
	private String companyname;
	private String contname;
	private String contno;
	public String getContname() {
		return contname;
	}
	public void setContname(String contname) {
		this.contname = contname;
	}
	public String getContno() {
		return contno;
	}
	public void setContno(String contno) {
		this.contno = contno;
	}
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	private String empName;
	private String userNameData;
	private String passwordData;
	public String getSernum() {
		return sernum;
	}
	public void setSernum(String sernum) {
		this.sernum = sernum;
	}
	public String getDatepick() {
		return datepick;
	}
	public void setDatepick(String datepick) {
		this.datepick = datepick;
	}
	
	
	public String getTenderNumber() {
		return tenderNumber;
	}
	public void setTenderNumber(String tenderNumber) {
		this.tenderNumber = tenderNumber;
	}
	
	public String getTender() {
		return tender;
	}
	public void setTender(String tender) {
		this.tender = tender;
	}
	public String getCalldat() {
		return calldat;
	}
	public void setCalldat(String calldat) {
		this.calldat = calldat;
	}
	public String getLastdat() {
		return lastdat;
	}
	public void setLastdat(String lastdat) {
		this.lastdat = lastdat;
	}
	public String getEmploy() {
		return employ;
	}
	public void setEmploy(String employ) {
		this.employ = employ;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getEmpName() {
		return empName;
	}
	public void setEmpName(String empName) {
		this.empName = empName;
	}
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
}