/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

public class HistoryForm extends ActionForm {
	
	private String message;
	private String year;
	private String fromdate;
	private String todate;
	private String userNameData;
	private String passwordData;
	private String slno1;
	private String date1;
	private String particulars1;
	private String invoice1;
	private String for12;
	private String amount1;
	private String transaction1;
	private String remarks1;
	private String process1;
	private String unit;
	private String unit1;
	private String companyname; 
	private String type;
	
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	private String year1;
	
	
	
	public String getUnit1() {
		return unit1;
	}
	public void setUnit1(String unit1) {
		this.unit1 = unit1;
	}
	public String getYear1() {
		return year1;
	}
	public void setYear1(String year1) {
		this.year1 = year1;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getProcess1() {
		return process1;
	}
	public void setProcess1(String process1) {
		this.process1 = process1;
	}
	public String getSlno1() {
		return slno1;
	}
	public void setSlno1(String slno1) {
		this.slno1 = slno1;
	}
	public String getDate1() {
		return date1;
	}
	public void setDate1(String date1) {
		this.date1 = date1;
	}
	public String getParticulars1() {
		return particulars1;
	}
	public void setParticulars1(String particulars1) {
		this.particulars1 = particulars1;
	}
	public String getInvoice1() {
		return invoice1;
	}
	public void setInvoice1(String invoice1) {
		this.invoice1 = invoice1;
	}
	public String getFor12() {
		return for12;
	}
	public void setFor12(String for12) {
		this.for12 = for12;
	}
	public String getAmount1() {
		return amount1;
	}
	public void setAmount1(String amount1) {
		this.amount1 = amount1;
	}
	public String getTransaction1() {
		return transaction1;
	}
	public void setTransaction1(String transaction1) {
		this.transaction1 = transaction1;
	}
	public String getRemarks1() {
		return remarks1;
	}
	public void setRemarks1(String remarks1) {
		this.remarks1 = remarks1;
	}
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameDta) {
		this.userNameData = userNameDta;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getYear() {
		return year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public String getFromdate() {
		return fromdate;
	}
	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}
	public String getTodate() {
		return todate;
	}
	public void setTodate(String todate) {
		this.todate = todate;
	}
	
	
}