/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import org.apache.struts.action.ActionForm;

/**
 * MyEclipse Struts Creation date: 06-19-2014
 * 
 * XDoclet definition:
 * 
 * @struts.form name="homeForm"
 */
public class HomeForm extends ActionForm {
	private static final long serialVersionUID = 1L;
	private String userNameData;
	private String passwordData;
	private String message;
	private String companyname;
	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getUserNameData() {
		return userNameData;
	}

	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}

	public String getPasswordData() {
		return passwordData;
	}

	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}