/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.forms;

import org.apache.struts.action.ActionForm;

public class PersonalhistoryForm extends ActionForm {
	private String userNameData;
	private String passwordData;
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
	private String slno;
	private String date1;
	private String desc;
	private int amount;
	private String remark;
	private int credit;
	private String year;
	private String fromdate;
	private String todate;
	public String getSlno() {
		return slno;
	}
	public void setSlno(String slno) {
		this.slno = slno;
	}
	public String getDate1() {
		return date1;
	}
	public void setDate1(String date1) {
		this.date1 = date1;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public int getAmount() {
		return amount;
	}
	public void setAmount(int amount) {
		this.amount = amount;
	}
	public int getCredit() {
		return credit;
	}
	public void setCredit(int credit) {
		this.credit = credit;
	}
	public String getYear() {
		return year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public String getFromdate() {
		return fromdate;
	}
	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}
	public String getTodate() {
		return todate;
	}
	public void setTodate(String todate) {
		this.todate = todate;
	}
}