package com.forms;


/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */


import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

public class TenderDisplayForm extends ActionForm {
	
	private String yeardetails;
	private String userName;
	private String empName;
	private String userNameData;
	private String passwordData;
	private String slno;
	private String dat1;
	private String tend;
	private String sub;
	private String lastdat;
	private String emd;
	private String docattach;
	private String userdoc;
	private String message;
	private FormFile file;
	private String slno1;
	private String unit;
	private String fromdate;
	private String todate;
	private String companyname;
	private String name;
	private String no;
	private String deleterec;
	public String getDeleterec() {
		return deleterec;
	}
	public void setDeleterec(String deleterec) {
		this.deleterec = deleterec;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getNo() {
		return no;
	}
	public void setNo(String no) {
		this.no = no;
	}
	
	public String getCompanyname() {
		return companyname;
	}
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}
	public String getUnit() {
		return unit;
	}
	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getFromdate() {
		return fromdate;
	}
	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}
	public String getTodate() {
		return todate;
	}
	public void setTodate(String todate) {
		this.todate = todate;
	}
	private String download;
	
	
	
	public String getDownload() {
		return download;
	}
	public void setDownload(String download) {
		this.download = download;
	}
	public String getSlno1() {
		return slno1;
	}
	public void setSlno1(String slno1) {
		this.slno1 = slno1;
	}
	public FormFile getFile() {
		return file;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getYeardetails() {
		return yeardetails;
	}
	public void setYeardetails(String yeardetails) {
		this.yeardetails = yeardetails;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getEmpName() {
		return empName;
	}
	public void setEmpName(String empName) {
		this.empName = empName;
	}
	public String getUserNameData() {
		return userNameData;
	}
	public void setUserNameData(String userNameData) {
		this.userNameData = userNameData;
	}
	public String getPasswordData() {
		return passwordData;
	}
	public void setPasswordData(String passwordData) {
		this.passwordData = passwordData;
	}
	public String getSlno() {
		return slno;
	}
	public void setSlno(String slno) {
		this.slno = slno;
	}
	public String getDat1() {
		return dat1;
	}
	public void setDat1(String dat1) {
		this.dat1 = dat1;
	}
	public String getTend() {
		return tend;
	}
	public void setTend(String tend) {
		this.tend = tend;
	}
	public String getSub() {
		return sub;
	}
	public void setSub(String sub) {
		this.sub = sub;
	}
	public String getLastdat() {
		return lastdat;
	}
	public void setLastdat(String lastdat) {
		this.lastdat = lastdat;
	}
	public String getEmd() {
		return emd;
	}
	public void setEmd(String emd) {
		this.emd = emd;
	}
	public String getDocattach() {
		return docattach;
	}
	public void setDocattach(String docattach) {
		this.docattach = docattach;
	}
	public String getUserdoc() {
		return userdoc;
	}
	public void setUserdoc(String userdoc) {
		this.userdoc = userdoc;
	}
	
	
	
}